### ISSUE TITLE
Hwo can I use flipper hooks

### ISSUE THREAD

**Issue by lopi-py** [littensy/roact-hooked-plus#2]
This project seems interesant, I've been using from today and I wanted to use flipper but I cant set values (just the initial one), the luau flipper returns as second parameter the motor used so you can do `motor.setGoal`. Also how can I use `useAnimation`, I didn't understand it very well.

**Comment by littensy** [comment]
If you want to use flipper, I recommend `useSingleMotor` or `useGroupMotor`:

```ts
const [value, setGoal, motor] = useSingleMotor(0);
useEffect(() => {
  setGoal(new Spring(1));
}, []);

const [values, setGoals] = useGroupMotor({ x: 0, y: 0 });
useEffect(() => {
  setGoals({
    x: new Spring(1),
    y: new Spring(-1),
  });
}, []);
```
